const mongoose = require("mongoose");

const customerSchema = mongoose.Schema(
  {
    mobile_number: { type: String, unique: true, required: true },
    arpu_6: Number,
    arpu_7: Number,
    arpu_8: Number,
    onnet_mou_6: Number,
    onnet_mou_7: Number,
    onnet_mou_8: Number,
    offnet_mou_6: Number,
    offnet_mou_7: Number,
    offnet_mou_8: Number,
    roam_ic_mou_6: Number,
    roam_ic_mou_7: Number,
    roam_ic_mou_8: Number,
    roam_og_mou_6: Number,
    roam_og_mou_7: Number,
    roam_og_mou_8: Number,
    total_og_mou_6: Number,
    total_og_mou_7: Number,
    total_og_mou_8: Number,
    total_ic_mou_6: Number,
    total_ic_mou_7: Number,
    total_ic_mou_8: Number,
    total_rech_num_6: Number,
    total_rech_num_7: Number,
    total_rech_num_8: Number,
    total_rech_amt_6: Number,
    total_rech_amt_7: Number,
    total_rech_amt_8: Number,
    total_rech_data_6: Number,
    total_rech_data_7: Number,
    total_rech_data_8: Number,
    av_rech_amt_data_6: Number,
    av_rech_amt_data_7: Number,
    av_rech_amt_data_8: Number,
    aon: Number,
    sms_ic_6: Number,
    sms_ic_7: Number,
    sms_ic_8: Number,
    sms_og_6: Number,
    sms_og_7: Number,
    sms_og_8: Number,
    days_since_last_rech_6: Number,
    days_since_last_rech_7: Number,
    days_since_last_rech_8: Number,
    days_since_last_rech_data_6: Number,
    days_since_last_rech_data_7: Number,
    days_since_last_rech_data_8: Number,
    count_2g3g: Number,
    vol_2g3g: Number,
    monthly_2g3g: Number,
    segment: Number,
    churn: Boolean,
    pred_churn: Boolean,
  },
  { strict: false }
);

module.exports = mongoose.model("customer", customerSchema);
